### ISSUE TITLE
Add links to this repo in the page.

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/printers-status-webpage#7]
It could be helpful that webpage users could post an issue in this repo when they find trouble using the web. I propose the following:

1. Add a text below the button "Reserva aquí" that says, for example "Si crees que hay algún problema con la hoja de reservas de esta impresora, pon una incidencia [aquí](https://github.com/asrob-uc3m/printers-status-webpage/issues)".
 -This text should appear below the reservation button of each printer.
 -This text should appear only if the printer is Status = ok, that is the same behavior that the button "Reserva aquí".
 -This way, problems as https://github.com/asrob-uc3m/impresoras-asrob/issues/25 would be archived at the correct place.

2. Add a text at the end of the page that says "Si has detectado algún error en la página o tienes alguna sugerencia, ayúdanos a mejorar, poniendo una incidencia [aquí](https://github.com/asrob-uc3m/printers-status-webpage/issues)".
 -This way, we would obtain feedback from users.

What do you think about it?

**Comment by David-Estevez** [comment]
I have added your suggestions to the webpage in the following way:

1. Instead of a text, I have added a dropdown menu with options to report issues for the printer and the reservation document.
2. I have added the text exactly as you suggested.

I have updated the server, so the new page should already be available.
