### ISSUE TITLE
Add Dedalo to this page?

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/printers-status-webpage#8]
When Dédalo comes operative, it could be added to the reservation system. This Issue is to discuss this fact, and to decide if it would be a good idea or not.

**Comment by jgvictores** [comment]
LGTM!

**Comment by David-Estevez** [comment]
I already have added Dédalo to the reservation system (440d8742754adf0915573a4dc0ff589503dffdab). These changes have not been published yet to our website, since I need to link to the reservation document for Dédalo, which doesn't exist.

@Siotma / @jorgercobo please create that document and post the link here, and I will push these changes to master and publish them in our website.

**Comment by Siotma** [comment]
Reservation document must be created inside the ASROB account. I don't have those credentials so I can't do it.

**Comment by David-Estevez** [comment]
Credentials for both gmail and UC3M ASROB accounts can be found in the [private part of the wiki](http://asrob.uc3m.es/index.php/Medios_Sociales), as usual.

**Comment by Siotma** [comment]
My fault. [Here](https://docs.google.com/a/uc3m.es/spreadsheets/d/1fFE-khJqTYQlrFt21nMkbjPI9HMYCZ7zkc3aeEyo-Y8/edit?usp=sharing) can be found the new reservation sheet.

I also havee found [this helpful webpage](https://www.calendario-365.es/numero-de-semana.html) that tells the current week number.

**Comment by David-Estevez** [comment]
Fixed at b94b6e476512b85e3938dcd6b4517805d410b876

The [website](http://asrob.uc3m.es/printers/) has already been updated and features the new printer.

**Comment by Siotma** [comment]
There is still a thing left to do. Dedalo doesn't appear on the top bar of the page.

**Comment by David-Estevez** [comment]
My bad. Fixed at 1d9a2364ca356ec1b85372e3b7b6272709b809ec.

Thanks for spotting it!
